# Generated by Django 3.1.2 on 2021-06-09 17:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Altas_Equipos_Y_Componentes', '0001_initial'),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDeEquipo',
            fields=[
                ('IDE', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_de_asignacion', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha:')),
                ('nombre_responsable', models.CharField(max_length=255, verbose_name='Nombre responsable')),
                ('numero_de_empleado', models.CharField(max_length=100, verbose_name='No de empleado responsable')),
                ('status_responsable', models.BooleanField(default=False, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, max_length=255, null=True, verbose_name='Observaciones')),
                ('Registro_responsable_del_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.responsablearea', verbose_name='Jefe/Mando responsable de area')),
                ('asignacion_de_equipos', models.ManyToManyField(to='Altas_Equipos_Y_Componentes.EquipoYArticulos')),
                ('datos_generales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.responsableequipo', verbose_name='Datos generales respons')),
                ('oficio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cataoficio')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cataticket')),
            ],
            options={
                'verbose_name': 'Equipos asignados',
                'verbose_name_plural': 'Equipos asignados',
            },
        ),
    ]
