# Generated by Django 3.1.2 on 2021-06-01 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoDuro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Serie', models.CharField(max_length=255, unique=True, verbose_name='Serie')),
                ('Modelo', models.CharField(max_length=255, verbose_name='Modelo')),
                ('status', models.BooleanField(default=True, verbose_name='Disponible')),
                ('Marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catamarcasdm')),
                ('capacidad_de_disco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catacapaalmdis', verbose_name='Capacidad de almacenamiento GB/TB')),
                ('componente_nuevo_reuso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catanuevoreuso', verbose_name='Estado componente')),
                ('forma_de_adquisicion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cataformadqui', verbose_name='Forma de adquisición')),
                ('numero_de_contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catanumcontra', verbose_name='Número de contrato')),
                ('status_del_equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catastatus')),
                ('tipo_de_disco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catatipodis', verbose_name='Tipo de disco: SSD/HDD')),
                ('tipo_de_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catatiporegist', verbose_name='Tipo de registro')),
                ('velocidad_disco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catavelocdis', verbose_name='Tamaño de disco duro')),
            ],
            options={
                'verbose_name': 'Disco Duro',
                'verbose_name_plural': 'Disco Duro',
            },
        ),
        migrations.CreateModel(
            name='MemoriaRam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Serie', models.CharField(max_length=255, unique=True, verbose_name='Serie')),
                ('Modelo', models.CharField(max_length=255, verbose_name='Modelo')),
                ('status', models.BooleanField(default=True, verbose_name='Disponible')),
                ('Marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catamarcasdm', verbose_name='Marca')),
                ('capacidad_ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catacaparam', verbose_name='Capacida de memoria GB')),
                ('componente_nuevo_reuso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catanuevoreuso', verbose_name='Estado componente')),
                ('forma_de_adquisicion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cataformadqui', verbose_name='Forma de adquisición')),
                ('numero_de_contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catanumcontra', verbose_name='Número de contrato')),
                ('status_del_equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catastatus')),
                ('tipo_de_memoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catatipoddr', verbose_name='Tipo de memoria DDR/2/3/4')),
                ('tipo_de_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catatiporegist', verbose_name='Tipo de registro')),
            ],
            options={
                'verbose_name': 'Memoria Ram',
                'verbose_name_plural': 'Memoria Ram',
            },
        ),
        migrations.CreateModel(
            name='EquipoYArticulos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave_cam', models.CharField(max_length=255, verbose_name='Clave cam')),
                ('serie', models.CharField(max_length=30, unique=True, verbose_name='Serie')),
                ('modelo', models.CharField(max_length=30, verbose_name='Modelo')),
                ('observaciones', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observaciones')),
                ('status', models.BooleanField(default=True, verbose_name='Disponible')),
                ('asignar_disco', models.ManyToManyField(blank=True, to='Altas_Equipos_Y_Componentes.DiscoDuro')),
                ('asignar_memoria', models.ManyToManyField(blank=True, to='Altas_Equipos_Y_Componentes.MemoriaRam')),
                ('asignar_pulgadas_pantalla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catapulgadas', verbose_name='Pulgadas pantalla')),
                ('asignar_sofware', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.sofware')),
                ('asigne_equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cataequipoarticulos', verbose_name='Equipo o articulo')),
                ('componente_nuevo_reuso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catanuevoreuso', verbose_name='Estado del equipo/componente')),
                ('forma_de_adquisicion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cataformadqui', verbose_name='Forma de adquisición')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catamarcasequitmp')),
                ('numero_de_contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catanumcontra', verbose_name='Número de contrato')),
                ('procesador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cataprocesador')),
                ('status_del_equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catastatus')),
                ('tipo_de_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catatiporegist', verbose_name='Tipo de registro')),
            ],
            options={
                'verbose_name': ' Equipos y Articulos',
                'verbose_name_plural': 'Equipos y Articulos',
            },
        ),
    ]
