# Generated by Django 3.1.2 on 2021-06-24 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Altas_Equipos_Y_Componentes', '0001_initial'),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Baja',
            fields=[
                ('Folio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_de_baja', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('Oficio', models.CharField(max_length=255, verbose_name='Oficio')),
                ('usuario', models.CharField(max_length=255, verbose_name='Usuario')),
                ('tecico_diacnosticador', models.CharField(max_length=255, verbose_name='Tecnico diacnosticador')),
                ('diagnostico', models.TextField(blank=True, max_length=255, null=True, verbose_name='Diagnóstico')),
                ('Adscripcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cataadscripcion')),
                ('asignacion_de_equipos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Altas_Equipos_Y_Componentes.equipoyarticulos', verbose_name='Equipo para baja:')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catacargobaja')),
                ('extencion_del_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cataextencion')),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cataperiodo')),
                ('status_baja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catastatusbaja')),
                ('telefono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catatelefono')),
                ('ticket_baja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cataticketbaja')),
            ],
            options={
                'verbose_name': 'Datos_Baja',
                'verbose_name_plural': 'Datos_Baja',
            },
        ),
    ]
