# Generated by Django 3.1.2 on 2021-06-01 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CataAdscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adscripccion', models.CharField(max_length=255, verbose_name='Adscripción')),
            ],
            options={
                'verbose_name': 'Catálogo adscripción',
                'verbose_name_plural': 'Catálogo Adscripción',
            },
        ),
        migrations.CreateModel(
            name='CataAntivirus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antivirus', models.CharField(max_length=50, verbose_name='Antivirus')),
            ],
            options={
                'verbose_name': 'Catálogo Antivirus',
                'verbose_name_plural': 'Software Antivirus',
            },
        ),
        migrations.CreateModel(
            name='CataCapaAlmDis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disco_capacidad', models.CharField(max_length=30, verbose_name='Asigne capacidad GB/TB')),
            ],
            options={
                'verbose_name': 'Catálogo capacidad almacenamiento',
                'verbose_name_plural': 'Catálogo capacidad almacenamiento',
            },
        ),
        migrations.CreateModel(
            name='CataCapaRam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad_de_memoria', models.CharField(max_length=30, verbose_name='Asigne capacida Gygabyte')),
            ],
            options={
                'verbose_name': 'Catálogo memoria ram capacidad',
                'verbose_name_plural': 'Catálogo memoria ram capacidad',
            },
        ),
        migrations.CreateModel(
            name='CataCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Catálogo cargos',
                'verbose_name_plural': 'Catálogo cargos',
            },
        ),
        migrations.CreateModel(
            name='CataCargoBaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Catálogo cargos',
                'verbose_name_plural': 'Catálogo cargos',
            },
        ),
        migrations.CreateModel(
            name='CataColores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Catálogo Colores',
                'verbose_name_plural': 'Catálogo Colores',
            },
        ),
        migrations.CreateModel(
            name='CataDireccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField(max_length=255, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Catálogo dirección',
                'verbose_name_plural': 'Catálogo Dirección',
            },
        ),
        migrations.CreateModel(
            name='CataEquipoArticulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_de_adquisicion', models.CharField(max_length=100, verbose_name='Forma de adquisición:')),
            ],
            options={
                'verbose_name': 'Catálogo Equipos y aditamentos',
                'verbose_name_plural': 'Catálogo Equipos y aditamentos',
            },
        ),
        migrations.CreateModel(
            name='CataExtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extencion', models.CharField(max_length=20, verbose_name='Extensión')),
            ],
            options={
                'verbose_name': 'Catálogo extensión',
                'verbose_name_plural': 'Catálogo extensión',
            },
        ),
        migrations.CreateModel(
            name='CataFormAdqui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_de_adquisicion', models.CharField(max_length=100, verbose_name='Forma de adquisición:')),
            ],
            options={
                'verbose_name': 'Catálogo forma de adquisición',
                'verbose_name_plural': 'Catálogo forma de adquisición',
            },
        ),
        migrations.CreateModel(
            name='CataIDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDE', models.CharField(max_length=255, verbose_name='IDE')),
            ],
            options={
                'verbose_name': 'Catálogo IDE',
                'verbose_name_plural': 'Catálogo IDE',
            },
        ),
        migrations.CreateModel(
            name='CataMarcasDM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=30, verbose_name='Asigne nombre de la marca')),
            ],
            options={
                'verbose_name': 'Catálogo marcas disco y ram',
                'verbose_name_plural': 'Catálogo  marcas disco y ram',
            },
        ),
        migrations.CreateModel(
            name='CataMarcasEquiTMP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=30, verbose_name='Asigne nombre de la marca')),
            ],
            options={
                'verbose_name': 'Catálogo marcas equipos y complementos',
                'verbose_name_plural': 'Catálogo marcas equipos y complementos',
            },
        ),
        migrations.CreateModel(
            name='CataNuevoReuso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_componente', models.CharField(max_length=30, verbose_name='Asigne: Nuevo/Reuso')),
            ],
            options={
                'verbose_name': 'Catálogo nuevo/Reuso',
                'verbose_name_plural': 'Catálogo Nuevo/Reuso',
            },
        ),
        migrations.CreateModel(
            name='CataNumContra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_numero', models.CharField(max_length=255, verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Catálogo número de contrato',
                'verbose_name_plural': 'Catálogo número de contrato',
            },
        ),
        migrations.CreateModel(
            name='CataOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=20, verbose_name='Office')),
            ],
            options={
                'verbose_name': 'Catálogo Offices',
                'verbose_name_plural': 'Software Offices',
            },
        ),
        migrations.CreateModel(
            name='CataOficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficio', models.CharField(max_length=255, verbose_name='Oficio')),
            ],
            options={
                'verbose_name': 'Catálogo Oficio',
                'verbose_name_plural': 'Catálogo Oficio',
            },
        ),
        migrations.CreateModel(
            name='CataPeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50, verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Catálogo periodo',
                'verbose_name_plural': 'Catálogo periodo',
            },
        ),
        migrations.CreateModel(
            name='CataProcesador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procesador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pulgadas')),
            ],
            options={
                'verbose_name': 'Catálogo procesador',
                'verbose_name_plural': 'Catálogo procesador',
            },
        ),
        migrations.CreateModel(
            name='Catapulgadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulgadas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pulgadas')),
            ],
            options={
                'verbose_name': 'Catálogo pulgadas',
                'verbose_name_plural': 'Catálogo pulgadas',
            },
        ),
        migrations.CreateModel(
            name='CataSistemaOperativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema_operativo', models.CharField(max_length=20, verbose_name='Sistema Operativo')),
            ],
            options={
                'verbose_name': 'Catálogo sistema operativos',
                'verbose_name_plural': 'Catálogo Software Sistema Operativo',
            },
        ),
        migrations.CreateModel(
            name='CataStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_del_equipo', models.CharField(max_length=50, verbose_name='Status del equipo:')),
            ],
            options={
                'verbose_name': 'Catálogo status del equipo',
                'verbose_name_plural': 'Catálogo status del equipo',
            },
        ),
        migrations.CreateModel(
            name='CataStatusBaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_baja', models.CharField(max_length=100, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Catálogo status baja',
                'verbose_name_plural': 'Catálogo status baja',
            },
        ),
        migrations.CreateModel(
            name='CataTelefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono No')),
            ],
            options={
                'verbose_name': 'Catálogo teléfono',
                'verbose_name_plural': 'Catálogo Teléfono',
            },
        ),
        migrations.CreateModel(
            name='CataTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=20, verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Catálogo ticket',
                'verbose_name_plural': 'Catálogo Ticket',
            },
        ),
        migrations.CreateModel(
            name='CataTicketBaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_baja', models.CharField(max_length=50, verbose_name='N Ticket baja')),
            ],
            options={
                'verbose_name': 'Catálogo tikect bajas',
                'verbose_name_plural': 'Catálogo tikect bajas',
            },
        ),
        migrations.CreateModel(
            name='CataTipoDDR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_memoria', models.CharField(max_length=30, verbose_name='Asigne DDR/2/3/4')),
            ],
            options={
                'verbose_name': 'Catálogo memoria Ram Tipo',
                'verbose_name_plural': 'Catálogo memoria Ram Tipo',
            },
        ),
        migrations.CreateModel(
            name='CataTipoDis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_disco', models.CharField(max_length=3, verbose_name='Asigne:SSD/HDD')),
            ],
            options={
                'verbose_name': 'Catálogo disco tipo',
                'verbose_name_plural': 'Catálogo tipo disco',
            },
        ),
        migrations.CreateModel(
            name='CataTipoRegist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_registro', models.CharField(max_length=30, verbose_name='Consumible/')),
            ],
            options={
                'verbose_name': 'Catálogo tipo de registro equipo',
                'verbose_name_plural': 'Catálogo de tipo registro equipo',
            },
        ),
        migrations.CreateModel(
            name='CataVelocDis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad', models.CharField(max_length=30, verbose_name='Asigne 2.5/3.5')),
            ],
            options={
                'verbose_name': 'Catálogo velocidad disco',
                'verbose_name_plural': 'Catálogo velocidad disco',
            },
        ),
        migrations.CreateModel(
            name='Sofware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Antivirus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cataantivirus', verbose_name='Antivirus')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cataoffice', verbose_name='Office')),
                ('sistema_operativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catasistemaoperativo', verbose_name='Sistema Operativo')),
            ],
            options={
                'verbose_name': 'Catálogo Software',
                'verbose_name_plural': 'Catálogo Software',
            },
        ),
        migrations.CreateModel(
            name='ResponsableEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adscripcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cataadscripcion')),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catadireccion', verbose_name='Ubicación del area')),
                ('extencion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cataextencion')),
                ('telefono_del_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catatelefono')),
            ],
            options={
                'verbose_name': 'Catálogo Datos generales',
                'verbose_name_plural': 'Catálogo Datos generales',
            },
        ),
        migrations.CreateModel(
            name='ResponsableArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('numero_de_empleado', models.CharField(max_length=20, verbose_name='Número de empleado')),
                ('adscripcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cataadscripcion')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catacargo')),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catadireccion', verbose_name='Ubicación del area')),
                ('extencion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.cataextencion')),
                ('telefono_del_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.catatelefono')),
            ],
            options={
                'verbose_name': 'Catálogo Responsable del area',
                'verbose_name_plural': 'Catálogo Responsable del area',
            },
        ),
    ]
